### ISSUE TITLE
where is the t2i code?

### ISSUE THREAD

**Issue by pokameng** [NUS-HPC-AI-Lab/OpenDiT#100]
hello,bro,I can not find the readme about how to train or inference t2i

**Comment by oahzxl** [comment]
sorry, we dont support that yet. maybe you can modify it yourself

**Comment by pokameng** [comment]
> sorry, we dont support that yet. maybe you can modify it yourself

okok ,thanks! By the way  ,support t2v?

**Comment by oahzxl** [comment]
yeah, you can try t2v using latte or vdit model

**Comment by pokameng** [comment]
> yeah, you can try t2v using latte or vdit model

Can you communicate on WeChat, if that's convenient. I just joined the group.
