### ISSUE TITLE
Any guide for inference with multi-GPU in OpenDiT

### ISSUE THREAD

**Issue by Anmuliar** [NUS-HPC-AI-Lab/OpenDiT#110]
Thanks for sharing such a great work! I ran OpenDiT inference on single A100 successfully. But it seems that the sample.py file do not support multi-GPU inference. How can I do inference with OpenDiT on multi-GPU properly.

**Comment by oahzxl** [comment]
will support tomorrow

**Comment by oahzxl** [comment]
it is supported now

**Comment by Anmuliar** [comment]
Many thanks! It works now.
