### ISSUE TITLE
如何使用ImageNet数据集训练DiT

### ISSUE THREAD

**Issue by Silentssss** [NUS-HPC-AI-Lab/OpenDiT#111]
您好，看到您的DiT模型支持使用ImageNet数据集训练，想复现您的结果，但是怎么修改数据集处理逻辑呢，您的文档里好像没有相关介绍
![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/108161275/db39e291-ad38-405a-9979-a9cddcbaf3b9)
![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/108161275/a163e83a-5b6d-496f-b38c-2c3e658958bf)

**Comment by oahzxl** [comment]
download imagenet and:

from torchvision.datasets import ImageFolder
dataset = ImageFolder(args.data_path, transform=)

**Comment by Silentssss** [comment]
好的，感谢
