### ISSUE TITLE
asking for video training and inference samples

### ISSUE THREAD

**Issue by chg0901** [NUS-HPC-AI-Lab/OpenDiT#55]
I just find that OpenVit support Video training and inference, is there any avaiable output samples?

**Comment by oahzxl** [comment]
we are still working on it. will be coming soon!

**Comment by chg0901** [comment]
Thank you ! We are thrilled to hear that Our MiniSora Community is planning to re-implement Sora, and we appreciate your recognition of OpenDiT as a strong baseline. Please keep us informed about any updates or improvements to OpenDiT.

**Comment by JACKHAHA363** [comment]
Hi thanks for working on it. Is there timeline or discord grup?

**Comment by oahzxl** [comment]
discord group is updated in readme
