### ISSUE TITLE
Text Encoder

### ISSUE THREAD

**Issue by ryancll** [NUS-HPC-AI-Lab/OpenDiT#57]
Thx for the wonderful work!

Do you have any plans to support T5 text encoder recently?

**Comment by scorpioliu** [comment]
need this too

**Comment by TinyTigerPan** [comment]
Thanks for your wonderful work! 
I think the T5 and text-to-image support will be widely needed.
Looking forward it!

**Comment by oahzxl** [comment]
thanks for your feedback. will update soon

**Comment by zhuyy1168** [comment]
need this too
need text-conditional like SDXL

**Comment by kabachuha** [comment]
Adding CLIP/T5 mix in https://github.com/NUS-HPC-AI-Lab/OpenDiT/pull/92

**Comment by oahzxl** [comment]
add t5 now
