### ISSUE TITLE
实时微信讨论组

### ISSUE THREAD

**Issue by akebest** [NUS-HPC-AI-Lab/OpenDiT#62]
群里很多搞DiT的，有啥问题可以实时讨论一下

![sora](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/135005135/92500b62-dcf6-413b-bdc6-b7798f627812)

**Comment by ilml** [comment]
人满了呢，能拉一下我吗感谢 微信 tom1ong

**Comment by hdjsjyl** [comment]
是的，人满了，请问方便加一下微信吗hourlei

**Comment by nankepan** [comment]
人满了，求拉感谢 微信 15619566149
