### ISSUE TITLE
ERROR: No matching distribution found for pyav

### ISSUE THREAD

**Issue by mbaloch** [NUS-HPC-AI-Lab/OpenDiT#64]
I am installing OpenDiT. At the `pip install -e .` for OpenDiT, I am getting the Error.

```
ERROR: Could not find a version that satisfies the requirement pyav (from opendit) (from versions: none)
ERROR: No matching distribution found for pyav
``` 

Can you help me resolve this?

**Comment by oahzxl** [comment]
it seems caused by conflict of dependency. maybe you can create a new env and install the requirements

**Comment by mbaloch** [comment]
I followed the installation steps in the repo to create a new conda environment. When I run `pip install -e` inside OpenDiT directory I get the following:
`INFO: pip is looking at multiple versions of opendit to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 11.0.1 Requires-Python >=3.9; 11.1.0 Requires-Python >=3.9; 11.2.0 Requires-Python >=3.9; 11.3.0 Requires-Python >=3.9; 11.4.0 Requires-Python >=3.9; 11.4.1 Requires-Python >=3.9; 12.0.0 Requires-Python >=3.9; 12.0.1 Requires-Python >=3.9; 12.0.2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement pyav (from opendit) (from versions: none)
ERROR: No matching distribution found for pyav`

**Comment by oahzxl** [comment]
maybe you can use python3.9

**Comment by mbaloch** [comment]
Same error on python 3.9 as well.

**Comment by oahzxl** [comment]
what error does it raise for python 3.9? maybe you can first install pyav and then install other packages

**Comment by mbaloch** [comment]
Thank you for your support. I discovered that the issue was with pip.
