### ISSUE TITLE
please fix spelling mistakes in README.md

### ISSUE THREAD

**Issue by JunyaoHu** [NUS-HPC-AI-Lab/OpenDiT#68]
see https://github.com/NUS-HPC-AI-Lab/OpenDiT/pull/67 @oahzxl

**Comment by oahzxl** [comment]
fixed now. thanks

**Comment by JunyaoHu** [comment]
<img width="169" alt="image" src="https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/67564714/95762261-66a2-4fc3-9905-ad6a6de25568">

还有这里，这里我改不了，您这边劳烦您操作一下。

**Comment by oahzxl** [comment]
ok, thanks!
