### ISSUE TITLE
Reproduction of DiT

### ISSUE THREAD

**Issue by WZDTHU** [NUS-HPC-AI-Lab/OpenDiT#70]
Thank you for your great work, and I have several issues:

First, I think this work is definitely going to improve the DiT training more efficiently. But I wonder whether this codebase could reproduce the results in the original DiT paper, such as FID.
![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/87896339/20abf1e7-a577-46bb-a237-ad0189b8d61d)

Second, I observed that global seed is used in the training of the original DiT implementation, as follows. In your implementation, global seed is not used in the train.py. Would this affect the reproducibility?
![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/87896339/fc6e1f8a-6bee-4929-aa29-97c76d4f4cee)

**Comment by oahzxl** [comment]
1. We have verified our accuracy on ImageNet. And we can achieve similar generation qualiy as the origin DiT. I think thats enough for us. We are now using our framework to train text-to-video models, which is more valuable for the current time being.
2. Seed will be always set in our framework when we launch.

**Comment by xyzhang626** [comment]
@oahzxl  Could you further add the FID you obtain and corresponding training steps with this repo into the README? I think that will be more attractive for people want to understand more about it. Thanks anyway, really good job.

**Comment by WZDTHU** [comment]
Thanks for your rapid reply.
I still feel puzzled about the global seed in OpenDiT/train.py.
As in the following figure, global_seed is only seen in add_argument(). How does this seed be set in your framework?
If I misunderstand the usage, could you provide more instructions?
Thank you.

![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/87896339/513d67ae-af0e-4e84-9a10-49856c35cf2f)

**Comment by oahzxl** [comment]
it will be set in colossai.launch. thanks for your suggestion, i will pass this arg to our launch func in future pr

**Comment by KKZ20** [comment]
We have already enabled passing the global seed during launch time, please check the latest commit! Thanks for your patience!

**Comment by WZDTHU** [comment]
Thanks for your attention and reply.
