### ISSUE TITLE
Training unconditional model for image and video generation

### ISSUE THREAD

**Issue by hdjsjyl** [NUS-HPC-AI-Lab/OpenDiT#80]
Hi Author,
Thanks for your excellent work. If I would like to train an unconditional image and video generation model, how should I modify the code? Thanks

**Comment by oahzxl** [comment]
can you further explain that what do you mean exactly of unconditional generation

**Comment by hdjsjyl** [comment]
No text input, thanks

**Comment by hdjsjyl** [comment]
hi @oahzxl , thanks for your reply. 
Unconditional model means the there is no text input for the model. 
Based on the original DiT, which supports both unconditional and conditional training. 
Thx

**Comment by oahzxl** [comment]
> hi @oahzxl , thanks for your reply. 
> 
> Unconditional model means the there is no text input for the model. 
> 
> Based on the original DiT, which supports both unconditional and conditional training. 
> 
> Thx

do you mean label input as origin DiT

**Comment by hdjsjyl** [comment]
Hi @oahzxl , thanks for your reply. 
    Yes it is about label input of original DiT. But I think this repo is about txt-based video/image generation, it should be no text input, no label input, just input image/video for image/video generation.

The following link includes the reply of the author of original DiT about unconditional training, thanks
https://github.com/facebookresearch/DiT/issues/18#issuecomment-1427265881

**Comment by oahzxl** [comment]
we use label generation by default in our example scripts

**Comment by hdjsjyl** [comment]
Thanks
