### ISSUE TITLE
Text inputs are different for image and video generation

### ISSUE THREAD

**Issue by hdjsjyl** [NUS-HPC-AI-Lab/OpenDiT#81]
Hi Author,
    In terms of the following code, does it mean the image generation only accepts the class input, not sentence/description input like an sentence? If not, I think the self.y_embedder should be the same as TextEmbedder(path=text_encoder, hidden_size=hidden_size) for text-based application. Thanks

        if self.use_video:
            self.x_embedder = PatchEmbed3D(patch_size, in_channels, embed_dim=hidden_size)
            self.t_embedder = TimestepEmbedder(hidden_size)
            self.y_embedder = TextEmbedder(path=text_encoder, hidden_size=hidden_size)
            self.num_patches = np.prod([input_size[i] // patch_size[i] for i in range(3)])
        else:
            self.x_embedder = PatchEmbed(input_size, patch_size, in_channels, hidden_size, bias=True)
            self.t_embedder = TimestepEmbedder(hidden_size)
            self.y_embedder = LabelEmbedder(num_classes, hidden_size, class_dropout_prob)
            self.num_patches = self.x_embedder.num_patches

**Comment by oahzxl** [comment]
we currently only support label conditioned image generation and text conditioned video generation

**Comment by hdjsjyl** [comment]
thanks
