### ISSUE TITLE
Can latte training load pretrained weight from Latte git repo? 

### ISSUE THREAD

**Issue by ersanliqiao** [NUS-HPC-AI-Lab/OpenDiT#82]

**Comment by oahzxl** [comment]
not for the current time because our latte model does not exacty match the origin one

**Comment by yhy-2000** [comment]
Could you release your pretrained weight of latte?

**Comment by oahzxl** [comment]
will be available soon, we are still working on the training

**Comment by oahzxl** [comment]
support now
